# Generated by Django 3.1.1 on 2020-11-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('grade', models.IntegerField()),
                ('rollno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
